services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumi-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      - REDIS_URL=redis://redis:${REDIS_PORT}
      - JAEGER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http
      - OTEL_SERVICE_NAME=lumi-backend
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_RESOURCE_ATTRIBUTES=service.name=lumi-backend,service.version=1.0.0,deployment.environment=${NODE_ENV}
      - OTEL_TRACES_SAMPLER=always_on
      - PORT=${BACKEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - API_PREFIX=${API_PREFIX}
      - CORS_ENABLED=${CORS_ENABLED}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - RATE_LIMIT_TTL=${RATE_LIMIT_TTL}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX}
      - PDF_DOWNLOAD_TIMEOUT=${PDF_DOWNLOAD_TIMEOUT}
      - PDF_MAX_SIZE=${PDF_MAX_SIZE}
      - PDF_CACHE_TTL=${PDF_CACHE_TTL}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - CACHE_TTL=${CACHE_TTL}
      - CACHE_MAX_ITEMS=${CACHE_MAX_ITEMS}
      - SECURITY_HEADERS_ENABLED=${SECURITY_HEADERS_ENABLED}
      - SECURITY_HEADERS_HSTS_ENABLED=${SECURITY_HEADERS_HSTS_ENABLED}
      - SECURITY_HEADERS_CSP_ENABLED=${SECURITY_HEADERS_CSP_ENABLED}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      jaeger:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:${BACKEND_PORT}/${API_PREFIX}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - lumi-network
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: lumi-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lumi-network

  redis:
    image: redis:6-alpine
    container_name: lumi-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lumi-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: lumi-jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "${JAEGER_UI_PORT}:${JAEGER_UI_PORT}"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_GRPC_ENABLED=true
      - COLLECTOR_OTLP_HTTP_ENABLED=true
    networks:
      - lumi-network

networks:
  lumi-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: